### ISSUE TITLE
Include header files in release

### ISSUE THREAD

**Issue by taljacob2** [taljacob2/oop#12]
when you release the library, you must include ALL the `.h` (and `.r`) files.

So when you release: you MUST "zip" the whole "src/oop" folder, so it would the
`.h` / `.r` files and `oop.a`.

---

See this reference that was in an old commit of `release.yml`.

```yml
name: Upload Release Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*-release'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip --junk-paths my-artifact README.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
```

![Image](https://user-images.githubusercontent.com/70590583/209690210-fb9cf091-ab65-4e45-af64-938bd05e6b47.png)
